import type { FruitConfig } from "@/types/game";

export const FRUITS: FruitConfig[] = [
  {
    name: "임병옥",
    radius: 17,
    color: "#5C0A2A",
    highlight: "#8B1A4A",
    scoreValue: 1,
    level: 0,
    decorations: [],
    image: "/players/0.png",
  },
  {
    name: "박한결",
    radius: 25,
    color: "#6B1035",
    highlight: "#9B2050",
    scoreValue: 3,
    level: 1,
    decorations: [],
    image: "/players/1.png",
  },
  {
    name: "서유신",
    radius: 33,
    color: "#7A1540",
    highlight: "#AA2A5A",
    scoreValue: 6,
    level: 2,
    decorations: [],
    image: "/players/2.png",
  },
  {
    name: "김웅빈",
    radius: 40,
    color: "#8B1A4A",
    highlight: "#B8446A",
    scoreValue: 10,
    level: 3,
    decorations: [],
    image: "/players/3.png",
  },
  {
    name: "박주홍",
    radius: 50,
    color: "#9A2055",
    highlight: "#C44E74",
    scoreValue: 15,
    level: 4,
    decorations: [],
    image: "/players/4.png",
  },
  {
    name: "김건희",
    radius: 58,
    color: "#A82860",
    highlight: "#D0587E",
    scoreValue: 21,
    level: 5,
    decorations: [],
    image: "/players/5.png",
  },
  {
    name: "송성문",
    radius: 68,
    color: "#B5306A",
    highlight: "#DC6288",
    scoreValue: 28,
    level: 6,
    decorations: [],
    image: "/players/6.png",
  },
  {
    name: "김혜성",
    radius: 78,
    color: "#C23875",
    highlight: "#E86C92",
    scoreValue: 36,
    level: 7,
    decorations: [],
    image: "/players/7.png",
  },
  {
    name: "이정후",
    radius: 90,
    color: "#D04080",
    highlight: "#F0769C",
    scoreValue: 45,
    level: 8,
    decorations: [],
    image: "/players/8.png",
  },
  {
    name: "김하성",
    radius: 104,
    color: "#DE488A",
    highlight: "#F880A6",
    scoreValue: 55,
    level: 9,
    decorations: [],
    image: "/players/9.png",
  },
  {
    name: "박병호",
    radius: 120,
    color: "#EC5095",
    highlight: "#FF8AB0",
    scoreValue: 66,
    level: 10,
    decorations: [],
    image: "/players/10.png",
  },
];

export const MAX_DROP_LEVEL = 5;

export function getRandomDropLevel(): number {
  return Math.floor(Math.random() * (MAX_DROP_LEVEL + 1));
}
